name: Deploy branch to RRP
description: Testing Deployments

inputs:
  branch-name:
    description: 'The name of the branch to deploy'
    required: true
  edgio-deploy-token:
    description: 'The deploy token for Edgio'
    required: true

secrets:
  EDGIO_DEPLOY_TOKEN:
    description: 'Deploy token for Edgio'

jobs:
  deploy-to-edgio:
    name: Deploy to Edgio
    runs-on: ubuntu-latest
    steps:
      - name: Check for Edgio deploy token secret
        run: |
          if [ -z "${{ inputs.edgio-deploy-token }}" ]; then
            echo "You must provide the EDGIO_DEPLOY_TOKEN secret."
            exit 1
          fi
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${{ inputs.branch-name }}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install packages
        run: npm ci
      - name: Deploy to Edgio
        run: |
          npm run deploy -- ${{'--branch=$BRANCH_NAME' || ''}} --token=${{ inputs.edgio-deploy-token }} \
          ${{github.event_name == 'push' && '--environment=default' || ''}} \
          ${{github.event_name == 'pull_request' && '--environment=staging' || ''}} \
          ${{github.event_name == 'release' && '--environment=production' || ''}}

